title: Speak For Me
email: info@speakforme.in
description: >
  TODO
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://speakforme.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: speakforme
github_username:  speakforme

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
