-
  name: PDS
  Department: |
    Department of Food and Public Distribution, India
  address: |
    Ministry of Consumer Affairs,
    Food and Public Distribution
    Department of Food & PD
    Krishi Bhawan,
    New Delhi - 110001.
    Phone: 23382504"
  email: asit.halder@nic.in
  twitter: jagograhakjago
-
  name: LPG
  department: Ministry of Petroleum and Natural Gas
  address: |
    Shri K.M.Mahesh
    Deputy Secretary (LPG)
    Ministry of Petroleum & Natural Gas
    Shastri Bhavan,
    New Delhi - 110001.(India)"
  email: mahesh.png@gov.in
  twitter: PetroleumMin
-
  name: MGNREGS
  department: Ministry of Rural Department
  address: |
    Smt Aparajita Sarangi,
    Joint Secretary
    Ministry of Rural Development
    Government of India
    Krishi Bhavan,
    Dr. Rajendra Prasad Road,
    New Delhi - 110001
  email: aparajitasarangi@gmail.com
  twitter: ""
-
  name: National Social Assistance Programme
  department: Ministry of Rural Department
  address: |
    Shri Manoranjan Kumar
    Eco. Adviser
    Ministry of Rural Development
    Government of India
    Krishi Bhavan,
    Dr. Rajendra Prasad Road,
    New Delhi - 110001
  email: manoranjan.kumar@nic.in
  twitter: ""
-
  name: PMJDY
  department: Ministry of Finance
  address: |
    Pradhan Mantri Jan Dhan Yojana,
    Department of Financial names,
    Ministry of Finance,
    Room No. 106,
    2nd Floor, JeevanDeep Building,
    Parliament Street,
    New Delhi-110001
    Phone: 011-23361571/23748738
  email: missionfi@nic.in
  twitter:
    FinMinIndia
    arunjaitley
-
  name: Employees Provident Fund Organisation (EPFO)
  department: Minister of State for Labour and Employment
  address: |
      Dr. V.P Joy, IAS
      Central P.F. Commissioner
      EPFO Head Office, New Delhi,
      Bhavishya Nidhi Bhawan,
      14, Bhikaiji Cama Place,
      New Delhi - 110 066"
  email: cpfc@epfindia.gov.in
  twitter: labourministry
-
  name: PAN
  department: Ministry of Finance (CBDT)
  address: |
    Shri Sushil Chandra
    Chairperson​​, Central Board of Direct Tax,
    Ministry of Finance,
    Room No. 106,
    2nd Floor, JeevanDeep Building,
    Parliament Street,
    New Delhi-110001
    Phone: 011-23361571/23748738
  email: >
    fmo@nic.in,
    chairman.cbdt@incometax.gov.in,
    rsecy@nic.in,
  twitter: >
    FinMinIndia
    arunjaitley
    adhia03
-
  name: Bank
