-
    Service: PDS
    Department: >
        Department of Food and Public Distribution, India
    Address: >
        Ministry of Consumer Affairs,
        Food and Public Distribution
        Department of Food & PD
        Krishi Bhawan,
        New Delhi - 110001.
        Phone: 23382504"
    Email: asit.halder@nic.in
    Twitter: jagograhakjago
-
    Service: LPG
    Department: Ministry of Petroleum and Natural Gas
    Address: >
        Shri K.M.Mahesh
        Deputy Secretary (LPG)
        Ministry of Petroleum & Natural Gas
        Shastri Bhavan,
        New Delhi - 110001.(India)"
    Email: mahesh.png@gov.in
    Twitter: PetroleumMin
-
    Service: MGNREGS
    Department: Ministry of Rural Department
    Address: >
        Smt Aparajita Sarangi,
        Joint Secretary 
        Ministry of Rural Development
        Government of India
        Krishi Bhavan,
        Dr. Rajendra Prasad Road,
        New Delhi - 110001
        INDIA
    Email: aparajitasarangi@gmail.com
    Twitter: ""
-
    Service: ""
    Department: ""
    Address: >
        Dr. Suparna S. Pachouri,
        Director 
        Ministry of Rural Development
        Government of India
        Krishi Bhavan,
        Dr. Rajendra Prasad Road,
        New Delhi - 110001
        INDIA
    Email: suparna.edu@nic.in
    Twitter: ""
-
    Service: National Social Assistance Programme
    Department: Ministry of Rural Department
    Address: >
        Shri Manoranjan Kumar
        Eco. Adviser
        Ministry of Rural Development
        Government of India
        Krishi Bhavan,
        Dr. Rajendra Prasad Road,
        New Delhi - 110001
        INDIA"
    Email: manoranjan.kumar@nic.in
    Twitter: ""
-
    Service: PMJDY
    Department: Ministry of Finance
    Address: >
        Pradhan Mantri Jan Dhan Yojana,
        Department of Financial Services,
        Ministry of Finance,
        Room No. 106,
        2nd Floor, JeevanDeep Building,
        Parliament Street,
        New Delhi-110001
        Phone: 011-23361571/23748738
    Email: missionfi@nic.in
    Twitter: 
        FinMinIndia
        arunjaitley
-
    Service: Employees Provident Fund Organisation (EPFO)
    Department: Minister of State for Labour and Employment
    Address: >
        Dr. V.P Joy, IAS
        Central P.F. Commissioner
        EPFO Head Office, New Delhi, 
        Bhavishya Nidhi Bhawan, 
        14, Bhikaiji Cama Place, 
        New Delhi - 110 066"
    Email: cpfc@epfindia.gov.in
    Twitter: labourministry
-
    Service: PAN
    Department: Ministry of Finance (CBDT)
    Address: >
        Shri Sushil Chandra
        Chairperson​​, Central Board of Direct Tax,
        Ministry of Finance,
        Room No. 106,
        2nd Floor, JeevanDeep Building,
        Parliament Street,
        New Delhi-110001
        Phone: 011-23361571/23748738
    Email: >
        fmo@nic.in,
        chairman.cbdt@incometax.gov.in,
        rsecy@nic.in,
    Twitter: >
        FinMinIndia
        arunjaitley
        adhia03